ALTER TABLE "api_scopes" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "api_scopes" ALTER COLUMN "api_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "api_scopes" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "api_scopes" ALTER COLUMN "description" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "apis" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "apis" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "apis" ALTER COLUMN "workspace_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "apis" ALTER COLUMN "current_signing_secret_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "apis" ALTER COLUMN "next_signing_secret_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "client_scopes" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "client_scopes" ALTER COLUMN "client_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "client_scopes" ALTER COLUMN "api_scope_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "client_secrets" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "client_secrets" ALTER COLUMN "secret" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "client_secrets" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "client_id_prefix" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "client_secret_prefix" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "workspace_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "for_workspace_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "api_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "current_client_secret_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "next_client_secret_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "data_encryption_keys" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "data_encryption_keys" ALTER COLUMN "key" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "signing_secrets" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "signing_secrets" ALTER COLUMN "secret" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "signing_secrets" ALTER COLUMN "iv" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "signing_secrets" ALTER COLUMN "algorithm" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "signing_secrets" ALTER COLUMN "status" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "workspace_billing_info" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "workspace_billing_info" ALTER COLUMN "workspace_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "workspace_billing_info" ALTER COLUMN "plan" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "workspace_billing_info" ALTER COLUMN "customer_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "name" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "tenant_id" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "data_encryption_key_id" SET DATA TYPE text;