/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AWSAccessKeyId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWSSecretAccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "AxiomApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkPublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DbUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DefaultSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Email": {
      "sender": string
      "type": "sst.aws.Email"
    }
    "JwksBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MessageDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MessageQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OptraApiId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OptraWorkspaceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "SchedulerFailedDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "StripeApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseAnonKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
  }
}
